name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Aggiorna ogni giorno a mezzanotte UTC
  workflow_dispatch:      # Permette di avviare manualmente l'azione

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@v3.0.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
